parameters:
    memcache.data_collector.class: Tqd\MemcacheBundle\DataCollector\MemcacheDataCollector
    memcache.data_collector.template: "TqdMemcacheBundle:Collector:memcache"

services:
    memcache.data_collector:
        class: "%memcache.data_collector.class%"
        tags:
            - { name: data_collector, template: "%memcache.data_collector.template%", id:"memcache"}
