language: php

php:
   - 5.6
   - hhvm

services:
   - memcached

before_script:
   - phpenv config-add .travis-php.ini
   - composer self-update
   - composer install --no-interaction

script:
   - vendor/bin/phpunit -c phpunit.xml.dist --coverage-text
