language: php

php:
   - 5.6

services:
   - memcached

before_script:
   - phpenv config-rm xdebug.ini
   - pecl install memcache
   - phpenv config-add .travis-php.ini
   - composer self-update || true
   # Ensure the memcache extension is available
   - composer show --platform ext-memcache
   - composer install --no-interaction

script:
   - vendor/bin/phpunit -c phpunit.xml.dist --coverage-text
