language: php

php:
   - 5.6
   - 7.0
   #- hhvm

services:
   - memcached

#env:
#   - PECL_MEMCACHE=memcache-3.0.6
#   - PECL_MEMCACHE=memcache-3.0.8

before_script:
   #- sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then yes "" | pecl install -f "$PECL_MEMCACHE"; fi;'
   # Need to activate memchached extension explictly to work with all versions.
   #- sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then phpenv config-add .travis-php.ini; fi;'
   - wget http://launchpadlibrarian.net/248151480/php-memcache_3.0.9~20151130.fdbd46b-2_amd64.deb
   - sudo dpkg -i php-memcache_3.0.9~20151130.fdbd46b-2_amd64.deb
   - phpenv config-rm xdebug.ini
   #- pecl install memcache
   - phpenv config-add .travis-php.ini
   - composer self-update || true
   # Ensure the memcache extension is available
   - composer show --platform ext-memcache
   - composer install --no-interaction

script:
   - vendor/bin/phpunit -c phpunit.xml.dist --coverage-text
