language: php

php:
   - 5.3
   - 5.4
   - 5.5
   - 5.6
   - 7.0
   #- hhvm

services:
   - memcached

env:
   - PECL_MEMCACHE=memcache-3.0.6
   - PECL_MEMCACHE=memcache-3.0.8

before_script:
   #- sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then yes "" | pecl install -f "$PECL_MEMCACHE"; fi;'
   # Need to activate memchached extension explictly to work with all versions.
   #- sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then phpenv config-add .travis-php.ini; fi;'
   - composer self-update || true
   # Ensure the memcache extension is available
   - composer show --platform ext-memcache
   - composer install --no-interaction

script:
   - vendor/bin/phpunit -c phpunit.xml.dist --coverage-text
